server:
    port: 8083

spring:
    datasource:
        username: root
        password: bjtu2024
        url: jdbc:mysql://39.106.39.209:3306/movie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 10
            minimum-idle: 5
            idle-timeout: 300000 # 5 minutes
            max-lifetime: 1800000 # 30 minutes
            connection-timeout: 30000 # 30 seconds
            leak-detection-threshold: 2000 # 2 seconds
    data:
        redis:
            port: 6379
            host: 39.106.39.209
    application:
        name: recommend-service-qb
    cloud:
        zookeeper:
            connect-string: 8.140.250.103:2181


jwt:
    secret: 1234567890123456
    expirationTime: 604800
    issuer: springboot3-security
    header: Authorization
    tokenHead: Bearer


springdoc:
    swagger-ui:
        path: /swagger-ui.html
        # path: 配置swagger-ui.html/UI界面的访问路径,默认为/swagger-ui.html
        tags-sorter: alpha
        # tags-sorter: 接口文档中的tags排序规则,默认为alpha,可选值为alpha(按字母顺序排序)或as-is(按照在代码中定义的顺序排序)
        operations-sorter: alpha

    api-docs:
        path: /v3/api-docs
        # path: 配置api-docs的访问路径,默认为/v3/api-docs



# knife4j项目访问访问地址:http://127.0.0.1:8080/doc.html#/home
knife4j:
    enable: true
    # 设置为true以启用Knife4j增强功能,这将再应用程序中启用Knife4j UI
    setting:
        # language: 设置Knife4j UI的语言,默认为zh_cn,可选值为zh_cn或en
        language: zh_cn
    #开启生产环境屏蔽
    production: false
    #是否启用登录认证
    basic:
        enable: true
        username: wck
        password: 123456