server:
  servlet:
    context-path: /api
  port: 8080
#  ssl:
#    key-alias: alias-key
#    key-store-password: 964fcclz
#    key-store-type: JKS
#    key-store: classpath:www.hyh31.top.jks
#    enabled: true

spring:
  datasource:
    username: root
    password: bjtu2024
    url: jdbc:mysql://39.106.39.209:3306/offer?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
  data:
    redis:
      port: 6379
      host: 39.106.39.209
